version: '3.7'

services:
  naming-server:
    image: dronworks/naming-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    networks:
      - currency-network

  currency-exchange:
    image: dronworks/currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
      spring.zipkin.base-url: http://zipkin-server:9411/
      RABBIT_URI: amqp:://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SERNDER_TYPE: rabbit

  currency-conversion:
    image: dronworks/currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - currency-exchange
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka # Also can be uppercase 
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/ # Also can be uppercase
      RABBIT_URI: amqp:://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SERNDER_TYPE: rabbit

  api-gateway:
    image: dronworks/api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
      spring.zipkin.base-url: http://zipkin-server:9411/ 
      RABBIT_URI: amqp:://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SERNDER_TYPE: rabbit

  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_limit: 500m
    ports: 
      - "9411:9411"
    networks:
      - currency-network
    depends_on:
      - rabbitmq
    restart: always
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672

  rabbitmq:
    image: rabbitmq:3.8-management
    mem_limit: 300m
    ports: 
      - "5672:5672"
      - "15672:15672"
    networks:
      - currency-network

  # zipkin-server:
  #   image: openzipkin/zipkin:2.23
  #   mem_limit: 500m
  #   ports:
  #     - "9411:9411"
  #   networks:
  #     - currency-network
  #   environment:
  #     RABBIT_URI: amqp://guest:guest@rabbitmq:5672
  #   depends_on:
  #     - rabbitmq
  #   restart: always
    
  # rabbitmq:
  #   image: rabbitmq:3.8-management
  #   mem_limit: 500m
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   networks:
  #     - currency-network

networks:
  currency-network: