version: '3.7'

services:
  naming-server:
    image: dronworks/naming-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    networks:
      - currency-network

  currency-exchange:
    image: dronworks/currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka

  currency-conversion:
    image: dronworks/currency-conversion-service:0.0.1-SNAPSHOT...
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - currency-exchange
    environment:
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
    

networks:
  currency-network: